<?xml version="1.0" encoding="utf-8"?><Database Name="FacturacionBryan" Class="FacturasDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=FacturacionBryan.mssql.somee.com;Initial Catalog=FacturacionBryan;Persist Security Info=True;User ID=MrBugsV_SQLLogin_2" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FacturacionBryanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categoria" Member="Categoria">
    <Type Name="Categoria">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Categoria_Producto" Member="Producto" ThisKey="Id" OtherKey="Categoria_Id" Type="Producto" />
    </Type>
  </Table>
  <Table Name="dbo.FacturaDetalle" Member="FacturaDetalle">
    <Type Name="FacturaDetalle">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Factura_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Producto_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Producto_FacturaDetalle" Member="Producto" ThisKey="Producto_Id" OtherKey="Id" Type="Producto" IsForeignKey="true" />
      <Association Name="FacturaCabecera_FacturaDetalle" Member="FacturaCabecera" ThisKey="Factura_Id" OtherKey="Id" Type="FacturaCabecera" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Producto" Member="Producto">
    <Type Name="Producto">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Categoria_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Producto_FacturaDetalle" Member="FacturaDetalle" ThisKey="Id" OtherKey="Producto_Id" Type="FacturaDetalle" />
      <Association Name="Categoria_Producto" Member="Categoria" ThisKey="Categoria_Id" OtherKey="Id" Type="Categoria" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.vProductos" Member="vProductos">
    <Type Name="vProductos">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreProducto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Stock" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="Categoria_Id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreCategoria" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Imagen" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.vFacturasDetalle" Member="vFacturasDetalle">
    <Type Name="vFacturasDetalle">
      <Column Name="IdFacturaCabecera" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="IdFacturaDetalle" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="NombreProducto" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Cantidad" Type="System.Decimal" DbType="Decimal(5,0)" CanBeNull="true" />
      <Column Name="Precio" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="NombreCategoria" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IdProducto" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.vFacturasCabecera" Member="vFacturasCabecera">
    <Type Name="vFacturasCabecera">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Cliente_Id" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Iva" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Anulado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Cliente" Member="Cliente">
    <Type Name="Cliente">
      <Column Name="Cedula" Type="System.String" DbType="NVarChar(13) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Postal" Type="System.String" DbType="NVarChar(5)" CanBeNull="true" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Cliente_FacturaCabecera" Member="FacturaCabecera" ThisKey="Cedula" OtherKey="Cliente_Id" Type="FacturaCabecera" />
      <Association Name="Cliente_LoginCliente" Member="LoginCliente" ThisKey="Cedula" OtherKey="Usuario" Type="LoginCliente" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.Empleado" Member="Empleado">
    <Type Name="Empleado">
      <Column Name="Cedula" Type="System.String" DbType="NVarChar(13) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Admin" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Empleado_FacturaCabecera" Member="FacturaCabecera" ThisKey="Cedula" OtherKey="Empleado_id" Type="FacturaCabecera" />
      <Association Name="Empleado_LoginEmpleado" Member="LoginEmpleado" ThisKey="Cedula" OtherKey="Usuario" Type="LoginEmpleado" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.FacturaCabecera" Member="FacturaCabecera">
    <Type Name="FacturaCabecera">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Cliente_Id" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Empleado_id" Type="System.String" DbType="NVarChar(13)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Subtotal" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Iva" Type="System.Decimal" DbType="Decimal(3,0)" CanBeNull="true" />
      <Column Name="Total" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="Anulado" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="FacturaCabecera_FacturaDetalle" Member="FacturaDetalle" ThisKey="Id" OtherKey="Factura_Id" Type="FacturaDetalle" />
      <Association Name="Cliente_FacturaCabecera" Member="Cliente" ThisKey="Cliente_Id" OtherKey="Cedula" Type="Cliente" IsForeignKey="true" />
      <Association Name="Empleado_FacturaCabecera" Member="Empleado" ThisKey="Empleado_id" OtherKey="Cedula" Type="Empleado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoginEmpleado" Member="LoginEmpleado">
    <Type Name="LoginEmpleado">
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(13) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Empleado_LoginEmpleado" Member="Empleado" ThisKey="Usuario" OtherKey="Cedula" Type="Empleado" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.LoginCliente" Member="LoginCliente">
    <Type Name="LoginCliente">
      <Column Name="Usuario" Type="System.String" DbType="NVarChar(13) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Contraseña" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Cliente_LoginCliente" Member="Cliente" ThisKey="Usuario" OtherKey="Cedula" Type="Cliente" IsForeignKey="true" />
    </Type>
  </Table>
</Database>